language: go

go:
  - 1.3
  - 1.4

install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/golang.org/x"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/github.com/tetrafolium/oauth2"
  - go get -v -t -d github.com/tetrafolium/oauth2/...

script:
  - go test -v github.com/tetrafolium/oauth2/...
